export const REQUIRED_FIELD_MESSAGE = 'This field is required';
export const CNIC_REGEX = /^\d{5}-\d{7}-\d{1}$/;
export const CNIC_ERROR_MESSAGE = 'CNIC must be in format XXXXX-XXXXXXX-X';
export const PHONE_NUMBER_REGEX = /^(\+92|0)?[0-9]{10}$/;
export const PHONE_NUMBER_ERROR_MESSAGE = 'Invalid phone number format';
export const SALARY_REGEX = /^\d+(\.\d{1,2})?$/;
export const SALARY_ERROR_MESSAGE = 'Invalid salary format';

// Student Options
export const gradeOptions = [
  { value: 'pre-k', label: 'Pre-K' },
  { value: 'kindergarten', label: 'Kindergarten' },
  { value: '1', label: 'Grade 1' },
  { value: '2', label: 'Grade 2' },
  { value: '3', label: 'Grade 3' },
  { value: '4', label: 'Grade 4' },
  { value: '5', label: 'Grade 5' },
  { value: '6', label: 'Grade 6' },
  { value: '7', label: 'Grade 7' },
  { value: '8', label: 'Grade 8' },
  { value: '9', label: 'Grade 9' },
  { value: '10', label: 'Grade 10' },
  { value: '11', label: 'Grade 11' },
  { value: '12', label: 'Grade 12' },
];

export const genderOptions = [
  { value: 'Male', label: 'Male' },
  { value: 'Female', label: 'Female' },
  { value: 'Other', label: 'Other' },
];

export const religionOptions = [
  { value: 'Islam', label: 'Islam' },
  { value: 'Christianity', label: 'Christianity' },
  { value: 'Hinduism', label: 'Hinduism' },
  { value: 'Buddhism', label: 'Buddhism' },
  { value: 'Sikhism', label: 'Sikhism' },
  { value: 'Judaism', label: 'Judaism' },
  { value: 'Other', label: 'Other' },
];

export const bloodGroupOptions = [
  { value: 'A+', label: 'A+' },
  { value: 'A-', label: 'A-' },
  { value: 'B+', label: 'B+' },
  { value: 'B-', label: 'B-' },
  { value: 'AB+', label: 'AB+' },
  { value: 'AB-', label: 'AB-' },
  { value: 'O+', label: 'O+' },
  { value: 'O-', label: 'O-' },
];

export const guardianRelationshipOptions = [
  { value: 'Father', label: 'Father' },
  { value: 'Mother', label: 'Mother' },
  { value: 'Brother', label: 'Brother' },
  { value: 'Sister', label: 'Sister' },
  { value: 'Aunt', label: 'Aunt' },
  { value: 'Uncle', label: 'Uncle' },
  { value: 'Cousin', label: 'Cousin' },
  { value: 'Nephew', label: 'Nephew' },
  { value: 'Niece', label: 'Niece' },
  { value: 'Grandmother', label: 'Grandmother' },
  { value: 'Grandfather', label: 'Grandfather' },
  { value: 'Charity Worker', label: 'Charity Worker' },
  { value: 'Sponsor', label: 'Sponsor' },
  { value: 'Neighbor', label: 'Neighbor' },
  { value: 'Other', label: 'Other' },
];

// Guardian Options
export const occupationOptions = [
  { value: 'Teacher', label: 'Teacher' },
  { value: 'Doctor', label: 'Doctor' },
  { value: 'Engineer', label: 'Engineer' },
  { value: 'Lawyer', label: 'Lawyer' },
  { value: 'Business Owner', label: 'Business Owner' },
  { value: 'Accountant', label: 'Accountant' },
  { value: 'Nurse', label: 'Nurse' },
  { value: 'Police Officer', label: 'Police Officer' },
  { value: 'Government Employee', label: 'Government Employee' },
  { value: 'Private Employee', label: 'Private Employee' },
  { value: 'Farmer', label: 'Farmer' },
  { value: 'Driver', label: 'Driver' },
  { value: 'Laborer', label: 'Laborer' },
  { value: 'Housewife', label: 'Housewife' },
  { value: 'Unemployed', label: 'Unemployed' },
  { value: 'Retired', label: 'Retired' },
  { value: 'Other', label: 'Other' },
];

export const educationLevelOptions = [
  { value: 'Illiterate', label: 'Illiterate' },
  { value: 'Primary', label: 'Primary' },
  { value: 'Middle', label: 'Middle' },
  { value: 'Matric', label: 'Matric' },
  { value: 'Intermediate', label: 'Intermediate' },
  { value: 'Bachelor', label: 'Bachelor' },
  { value: 'Master', label: 'Master' },
  { value: 'PhD', label: 'PhD' },
  { value: 'Other', label: 'Other' },
];

export const relationshipOptions = [
  { value: 'Father', label: 'Father' },
  { value: 'Mother', label: 'Mother' },
  { value: 'Brother', label: 'Brother' },
  { value: 'Sister', label: 'Sister' },
  { value: 'Aunt', label: 'Aunt' },
  { value: 'Uncle', label: 'Uncle' },
  { value: 'Cousin', label: 'Cousin' },
  { value: 'Nephew', label: 'Nephew' },
  { value: 'Niece', label: 'Niece' },
  { value: 'Grandmother', label: 'Grandmother' },
  { value: 'Grandfather', label: 'Grandfather' },
  { value: 'Charity Worker', label: 'Charity Worker' },
  { value: 'Sponsor', label: 'Sponsor' },
  { value: 'Neighbor', label: 'Neighbor' },
  { value: 'Other', label: 'Other' },
];

// Staff Options
export const designationOptions = [
  { value: 'Principal', label: 'Principal' },
  { value: 'Vice Principal', label: 'Vice Principal' },
  { value: 'Head Teacher', label: 'Head Teacher' },
  { value: 'Senior Teacher', label: 'Senior Teacher' },
  { value: 'Teacher', label: 'Teacher' },
  { value: 'Assistant Teacher', label: 'Assistant Teacher' },
  { value: 'Subject Specialist', label: 'Subject Specialist' },
  { value: 'Librarian', label: 'Librarian' },
  { value: 'Lab Assistant', label: 'Lab Assistant' },
  { value: 'Accountant', label: 'Accountant' },
  { value: 'Clerk', label: 'Clerk' },
  { value: 'Security Guard', label: 'Security Guard' },
  { value: 'Janitor', label: 'Janitor' },
  { value: 'Driver', label: 'Driver' },
  { value: 'Cook', label: 'Cook' },
  { value: 'Other', label: 'Other' },
];

export const staffStatusOptions = [
  { value: 'Active', label: 'Active' },
  { value: 'On Leave', label: 'On Leave' },
  { value: 'Suspended', label: 'Suspended' },
  { value: 'Resigned', label: 'Resigned' },
  { value: 'Terminated', label: 'Terminated' },
  { value: 'Retired', label: 'Retired' },
];

export const maritalStatusOptions = [
  { value: 'Single', label: 'Single' },
  { value: 'Married', label: 'Married' },
  { value: 'Divorced', label: 'Divorced' },
  { value: 'Widowed', label: 'Widowed' },
];

// Concession, Allowance, Deduction Options
export const statusOptions = [
  { value: 'Active', label: 'Active' },
  { value: 'Inactive', label: 'Inactive' },
];

export const applicableToOptions = [
  { value: 'Staff', label: 'Staff' },
  { value: 'Student', label: 'Student' },
  { value: 'Both', label: 'Both' },
];

export const allowanceTypeOptions = [
  { value: 'Housing', label: 'Housing' },
  { value: 'Transport', label: 'Transport' },
  { value: 'Medical', label: 'Medical' },
  { value: 'Education', label: 'Education' },
  { value: 'Other', label: 'Other' },
];

export const deductionTypeOptions = [
  { value: 'Tax', label: 'Tax' },
  { value: 'Insurance', label: 'Insurance' },
  { value: 'Loan', label: 'Loan' },
  { value: 'Advance', label: 'Advance' },
  { value: 'Other', label: 'Other' },
];

// Student Data
export const studentsData = [
  {
    id: 1,
    fullName: 'John Doe',
    surname: 'Doe',
    rollNumber: 'RN001',
    registrationNumber: 'REG001',
    grade: 'Grade 10',
    gender: 'Male',
    dateOfBirth: '2010-05-15',
    admissionDate: '2023-09-01',
    guardianName: 'Robert Doe',
    guardianRelationship: 'Father',
  },
  {
    id: 2,
    fullName: 'Jane Smith',
    surname: 'Smith',
    rollNumber: 'RN002',
    registrationNumber: 'REG002',
    grade: 'Grade 11',
    gender: 'Female',
    dateOfBirth: '2009-08-20',
    admissionDate: '2022-09-01',
    guardianName: 'Mary Smith',
    guardianRelationship: 'Mother',
    email: 'jane.smith@example.com',
    phone: '+1 (555) 234-5678',
  },
  {
    id: 3,
    fullName: 'Alice Johnson',
    surname: 'Johnson',
    rollNumber: 'RN003',
    registrationNumber: 'REG003',
    grade: 'Grade 9',
    gender: 'Female',
    dateOfBirth: '2011-03-10',
    admissionDate: '2024-09-01',
    guardianName: 'David Johnson',
    guardianRelationship: 'Father',
    email: 'alice.johnson@example.com',
    phone: '+1 (555) 345-6789',
  },
  {
    id: 4,
    fullName: 'Bob Williams',
    surname: 'Williams',
    rollNumber: 'RN004',
    registrationNumber: 'REG004',
    grade: 'Grade 12',
    gender: 'Male',
    dateOfBirth: '2008-11-25',
    admissionDate: '2021-09-01',
    guardianName: 'Sarah Williams',
    guardianRelationship: 'Mother',
    email: 'bob.williams@example.com',
    phone: '+1 (555) 456-7890',
  },
  {
    id: 5,
    fullName: 'Charlie Brown',
    surname: 'Brown',
    rollNumber: 'RN005',
    registrationNumber: 'REG005',
    grade: 'Grade 10',
    gender: 'Male',
    dateOfBirth: '2010-07-12',
    admissionDate: '2023-09-01',
    guardianName: 'Emma Brown',
    guardianRelationship: 'Mother',
    email: 'charlie.brown@example.com',
    phone: '+1 (555) 567-8901',
  },
  {
    id: 6,
    fullName: 'Diana Prince',
    surname: 'Prince',
    rollNumber: 'RN006',
    registrationNumber: 'REG006',
    grade: 'Grade 11',
    gender: 'Female',
    dateOfBirth: '2009-12-05',
    admissionDate: '2022-09-01',
    guardianName: 'Michael Prince',
    guardianRelationship: 'Father',
    email: 'diana.prince@example.com',
    phone: '+1 (555) 678-9012',
  },
  {
    id: 7,
    fullName: 'Edward Norton',
    surname: 'Norton',
    rollNumber: 'RN007',
    registrationNumber: 'REG007',
    grade: 'Grade 9',
    gender: 'Male',
    dateOfBirth: '2011-01-18',
    admissionDate: '2024-09-01',
    guardianName: 'Lisa Norton',
    guardianRelationship: 'Mother',
    email: 'edward.norton@example.com',
    phone: '+1 (555) 789-0123',
  },
  {
    id: 8,
    fullName: 'Fiona Apple',
    surname: 'Apple',
    rollNumber: 'RN008',
    registrationNumber: 'REG008',
    grade: 'Grade 12',
    gender: 'Female',
    dateOfBirth: '2008-09-30',
    admissionDate: '2021-09-01',
    guardianName: 'James Apple',
    guardianRelationship: 'Father',
    email: 'fiona.apple@example.com',
    phone: '+1 (555) 890-1234',
  },
  {
    id: 9,
    fullName: 'George Lucas',
    surname: 'Lucas',
    rollNumber: 'RN009',
    registrationNumber: 'REG009',
    grade: 'Grade 10',
    gender: 'Male',
    dateOfBirth: '2010-04-22',
    admissionDate: '2023-09-01',
    guardianName: 'Patricia Lucas',
    guardianRelationship: 'Mother',
    email: 'george.lucas@example.com',
    phone: '+1 (555) 901-2345',
  },
  {
    id: 10,
    fullName: 'Helen Mirren',
    surname: 'Mirren',
    rollNumber: 'RN010',
    registrationNumber: 'REG010',
    grade: 'Grade 11',
    gender: 'Female',
    dateOfBirth: '2009-06-14',
    admissionDate: '2022-09-01',
    guardianName: 'Thomas Mirren',
    guardianRelationship: 'Father',
    email: 'helen.mirren@example.com',
    phone: '+1 (555) 012-3456',
  },
  {
    id: 11,
    fullName: 'Ian McKellen',
    surname: 'McKellen',
    rollNumber: 'RN011',
    registrationNumber: 'REG011',
    grade: 'Grade 9',
    gender: 'Male',
    dateOfBirth: '2011-02-28',
    admissionDate: '2024-09-01',
    guardianName: 'Jennifer McKellen',
    guardianRelationship: 'Mother',
    email: 'ian.mckellen@example.com',
    phone: '+1 (555) 123-4568',
  },
  {
    id: 12,
    fullName: 'Julia Roberts',
    surname: 'Roberts',
    rollNumber: 'RN012',
    registrationNumber: 'REG012',
    grade: 'Grade 12',
    gender: 'Female',
    dateOfBirth: '2008-10-08',
    admissionDate: '2021-09-01',
    guardianName: 'Christopher Roberts',
    guardianRelationship: 'Father',
    email: 'julia.roberts@example.com',
    phone: '+1 (555) 234-5679',
  },
];

// Guardian Data
export const guardiansData = [
  {
    id: 1,
    fullName: 'Robert Doe',
    cnic: '12345-1234567-1',
    phoneNumber: '+92 300 1234567',
    occupation: 'Engineer',
    profilePicture: null,
  },
  {
    id: 2,
    fullName: 'Mary Smith',
    cnic: '23456-2345678-2',
    phoneNumber: '+92 301 2345678',
    occupation: 'Teacher',
    profilePicture: null,
  },
  {
    id: 3,
    fullName: 'David Johnson',
    cnic: '34567-3456789-3',
    phoneNumber: '+92 302 3456789',
    occupation: 'Doctor',
    profilePicture: null,
  },
  {
    id: 4,
    fullName: 'Sarah Williams',
    cnic: '45678-4567890-4',
    phoneNumber: '+92 303 4567890',
    occupation: 'Business Owner',
    profilePicture: null,
  },
  {
    id: 5,
    fullName: 'Emma Brown',
    cnic: '56789-5678901-5',
    phoneNumber: '+92 304 5678901',
    occupation: 'Housewife',
    profilePicture: null,
  },
  {
    id: 6,
    fullName: 'Michael Prince',
    cnic: '67890-6789012-6',
    phoneNumber: '+92 305 6789012',
    occupation: 'Lawyer',
    profilePicture: null,
  },
  {
    id: 7,
    fullName: 'Lisa Norton',
    cnic: '78901-7890123-7',
    phoneNumber: '+92 306 7890123',
    occupation: 'Nurse',
    profilePicture: null,
  },
  {
    id: 8,
    fullName: 'James Apple',
    cnic: '89012-8901234-8',
    phoneNumber: '+92 307 8901234',
    occupation: 'Accountant',
    profilePicture: null,
  },
  {
    id: 9,
    fullName: 'Patricia Lucas',
    cnic: '90123-9012345-9',
    phoneNumber: '+92 308 9012345',
    occupation: 'Teacher',
    profilePicture: null,
  },
  {
    id: 10,
    fullName: 'Thomas Mirren',
    cnic: '01234-0123456-0',
    phoneNumber: '+92 309 0123456',
    occupation: 'Government Employee',
    profilePicture: null,
  },
];

// Staff Data
export const staffData = [
  {
    id: 1,
    fullName: 'Ahmed Khan',
    surname: 'Khan',
    cnic: '12345-1234567-1',
    phoneNumber: '+92 300 1234567',
    designation: 'Principal',
    status: 'Active',
    gender: 'Male',
    profilePicture: null,
  },
  {
    id: 2,
    fullName: 'Fatima Ali',
    surname: 'Ali',
    cnic: '23456-2345678-2',
    phoneNumber: '+92 301 2345678',
    designation: 'Head Teacher',
    status: 'Active',
    gender: 'Female',
    profilePicture: null,
  },
  {
    id: 3,
    fullName: 'Hassan Raza',
    surname: 'Raza',
    cnic: '34567-3456789-3',
    phoneNumber: '+92 302 3456789',
    designation: 'Senior Teacher',
    status: 'Active',
    gender: 'Male',
    profilePicture: null,
  },
  {
    id: 4,
    fullName: 'Ayesha Malik',
    surname: 'Malik',
    cnic: '45678-4567890-4',
    phoneNumber: '+92 303 4567890',
    designation: 'Teacher',
    status: 'Active',
    gender: 'Female',
    profilePicture: null,
  },
  {
    id: 5,
    fullName: 'Usman Shah',
    surname: 'Shah',
    cnic: '56789-5678901-5',
    phoneNumber: '+92 304 5678901',
    designation: 'Accountant',
    status: 'Active',
    gender: 'Male',
    profilePicture: null,
  },
];

// Concession Data
export const concessionsData = [
  {
    id: 1,
    name: 'Sibling Discount',
    amount: '5000.00',
    description: 'Discount for siblings enrolled in the same school',
    status: 'Active',
    applicableTo: 'Student',
  },
  {
    id: 2,
    name: 'Merit Scholarship',
    amount: '10000.00',
    description: 'Scholarship for students with excellent academic performance',
    status: 'Active',
    applicableTo: 'Student',
  },
  {
    id: 3,
    name: 'Staff Child Discount',
    amount: '7500.00',
    description: 'Discount for children of school staff members',
    status: 'Active',
    applicableTo: 'Student',
  },
  {
    id: 4,
    name: 'Early Payment Discount',
    amount: '2000.00',
    description: 'Discount for early fee payment',
    status: 'Active',
    applicableTo: 'Student',
  },
  {
    id: 5,
    name: 'Need-Based Financial Aid',
    amount: '15000.00',
    description: 'Financial assistance for students in need',
    status: 'Active',
    applicableTo: 'Student',
  },
];

// Allowance Data
export const allowancesData = [
  {
    id: 1,
    name: 'Housing Allowance',
    amount: '25000.00',
    description: 'Monthly housing allowance for staff',
    status: 'Active',
    type: 'Housing',
  },
  {
    id: 2,
    name: 'Transport Allowance',
    amount: '10000.00',
    description: 'Monthly transport allowance for staff',
    status: 'Active',
    type: 'Transport',
  },
  {
    id: 3,
    name: 'Medical Allowance',
    amount: '15000.00',
    description: 'Monthly medical allowance for staff',
    status: 'Active',
    type: 'Medical',
  },
  {
    id: 4,
    name: 'Education Allowance',
    amount: '20000.00',
    description: 'Education allowance for staff children',
    status: 'Active',
    type: 'Education',
  },
  {
    id: 5,
    name: 'Special Allowance',
    amount: '5000.00',
    description: 'Special monthly allowance',
    status: 'Active',
    type: 'Other',
  },
];

// Deduction Data
export const deductionsData = [
  {
    id: 1,
    name: 'Income Tax',
    amount: '5000.00',
    description: 'Monthly income tax deduction',
    status: 'Active',
    type: 'Tax',
  },
  {
    id: 2,
    name: 'Health Insurance',
    amount: '3000.00',
    description: 'Monthly health insurance premium',
    status: 'Active',
    type: 'Insurance',
  },
  {
    id: 3,
    name: 'Provident Fund',
    amount: '8000.00',
    description: 'Monthly provident fund contribution',
    status: 'Active',
    type: 'Other',
  },
  {
    id: 4,
    name: 'Loan Deduction',
    amount: '10000.00',
    description: 'Monthly loan repayment',
    status: 'Active',
    type: 'Loan',
  },
  {
    id: 5,
    name: 'Advance Salary',
    amount: '15000.00',
    description: 'Advance salary deduction',
    status: 'Active',
    type: 'Advance',
  },
];

